package rs.ac.bg.etf.pp1;

import java_cup.runtime.*;
import org.apache.log4j.*;
import rs.ac.bg.etf.pp1.ast.*;

parser code {:

	boolean errorDetected;
	
	Logger log = Logger.getLogger(getClass());
        
    public void report_fatal_error(String message, Object info) throws java.lang.Exception {
      done_parsing();
      report_error(message, info);
    }
  
    public void syntax_error(Symbol cur_token) {
        report_error("\nsintaksna greska", cur_token);
    }
  
    public void unrecovered_syntax_error(Symbol cur_token) throws java.lang.Exception {
        report_fatal_error("fatalna greska, parsiranje se ne moze nastaviti", cur_token);
    }

    public void report_error(String message, Object info) {
    	errorDetected = true;
    	StringBuilder msg = new StringBuilder(message); 
    	if (info instanceof Symbol)
            msg.append (" na liniji ").append(((Symbol)info).left);
        log.error(msg.toString());
    }
:}


init with {:
	errorDetected = false;
:}

scan with {:
	Symbol s = this.getScanner().next_token();
	if (s != null && s.value != null) 
		log.info(s.toString() + " " + s.value.toString());
	return s;
:}

terminal PROG, BREAK, ELSE, CONST, IF, NEW, PRINT, READ, RETURN, VOID, CONT, FOR, LEN, MAP, FINDANY,
         PLUS, MINUS, MULT, DIV, MOD,
         EQ, NEQ, GT, GTE, LT, LTE, 
         AND, OR, ASSIGN, INC, DEC,
         SEMI, COLON, COMMA, DOT, 
         LPAREN, RPAREN, LBRACKET, RBRACKET, LBRACE, RBRACE, 
         QUESTION, ARROW;

terminal Integer NUMBER, BOOL;
terminal Character CHARACTER;
terminal String IDENT;

nonterminal rs.etf.pp1.symboltable.concepts.Obj Designator, DesignatorArr, MethRetAndName;

nonterminal rs.etf.pp1.symboltable.concepts.Struct Expr, Term, Factor, FactorSub,
            MulopFactorList, AddopTermList, CondFact, CondFactList, CondTerm,
            CondTermList, Condition, ActParsOne;

nonterminal Program, ConstDecl, VarDecl, MethodDecl, FormPars, Type, Statement, DesignatorStatement,
            ActPars,
            Assignop, Relop, Addop, Mulop;
			
nonterminal ProgramName, ConstVarDeclList, MethodDeclList, ConstDeclOne, ConstDeclMore, FormParsOne, VarDeclOne, VarDeclMore, VarDeclListRec, StatementList, ElseStmt, Statements, ActParsMore, SingleStatement, Constant, ForInit, ForCondition, ForStep, IfCondition;

nonterminal ElseMark, ForCondMark, ForStepMark, ForBodyMark, TernaryMark, MapMark;

precedence left ELSE;

Program ::= (Program) PROG ProgramName ConstVarDeclList LBRACE MethodDeclList RBRACE;

ProgramName ::= (ProgramName) IDENT;

ElseMark    ::= (ElseMark) /* epsilon */ ;
ForCondMark ::= (ForCondMark) /* epsilon */ ;
ForStepMark ::= (ForStepMark) /* epsilon */ ;
ForBodyMark ::= (ForBodyMark) /* epsilon */ ;
TernaryMark ::= (TernaryMark) /* epsilon */ ;
MapMark     ::= (MapMark) /* epsilon */ ;

ConstVarDeclList ::= 	(ConstVarDeclList_con) ConstVarDeclList ConstDecl
						|
						(ConstVarDeclList_var) ConstVarDeclList VarDecl
						|
						(ConstVarDeclList_e) /* epsilon */
						;
				
ConstDecl ::= (ConstDecl) CONST Type ConstDeclOne ConstDeclMore SEMI;

ConstDeclOne ::= (ConstDeclOne) IDENT ASSIGN Constant;

ConstDeclMore ::= 	(ConstDeclMore_comma) COMMA ConstDeclOne ConstDeclMore
					|
					(ConstDeclMore_e) /* epsilon */
					;

Constant ::= 	(Constant_n) NUMBER
				|
				(Constant_c) CHARACTER
				|
				(Constant_b) BOOL
				;
				
VarDecl ::= (VarDecl) Type VarDeclOne VarDeclMore SEMI;


VarDeclOne ::= 	(VarDeclOne_var) IDENT  
				|
				(VarDeclOne_array) IDENT LBRACKET RBRACKET
				; 


VarDeclMore ::= (VarDeclMore_comma) COMMA VarDeclOne VarDeclMore 
				|
				(VarDeclMore_e) /* epsilon */
				; 
				
Type ::= (Type) IDENT;

MethodDeclList ::= 	(MethodDeclList_rec) MethodDeclList MethodDecl
					|
					(MethodDeclList_e)
					;

MethodDecl ::=  (MethodDecl_fp) MethRetAndName LPAREN FormPars RPAREN VarDeclListRec LBRACE StatementList RBRACE
                |
                (MethodDecl_nfp) MethRetAndName LPAREN RPAREN VarDeclListRec LBRACE StatementList RBRACE
                ;

MethRetAndName ::= 	(MethRetAndName_type) Type IDENT
					|
					(MethRetAndName_void) VOID IDENT
					;
				
FormParsOne ::= (FormParsOne_var) Type IDENT  
			|
			(FormParsOne_array) Type IDENT LBRACKET RBRACKET
			|
			(FormParsOne_error) error:e
			{: parser.report_error("oporavak od greske u deklaraciji formalnog parametra. linija: " + eleft, null); :}
			; 

FormPars ::= 	(FormPars_rec) FormPars COMMA FormParsOne
				|
				(FormPars_one) FormParsOne
				;


VarDeclListRec ::= 	(VarDeclListRec_rec) VarDeclListRec VarDecl
					|
					(VarDeclListRec_e) /* epsilon */
					;

StatementList ::= 	(StatementList_rec) StatementList Statement
				   	|										   
				  	(StatementList_e) /* epsilon */
				   	;

Statement ::= (Statement_ss) SingleStatement
			  |
			  (Statement_s) Statements
			  ;

SingleStatement ::= (SingleStatement_ds) DesignatorStatement SEMI
					|
					(SingleStatement_if) IF LPAREN IfCondition RPAREN Statement ElseStmt
					|
					(SingleStatement_break) BREAK SEMI
					|
					(SingleStatement_continue) CONT SEMI
					|
					(SingleStatement_return1) RETURN SEMI
			  		|
			  		(SingleStatement_return2) RETURN Expr SEMI
			  		|
			  		(SingleStatement_read) READ LPAREN Designator RPAREN SEMI
			  		|
			  		(SingleStatement_print1) PRINT LPAREN Expr RPAREN SEMI
			  		|
			  		(SingleStatement_print2) PRINT LPAREN Expr COMMA NUMBER RPAREN SEMI
					|
					(SingleStatement_for) FOR LPAREN ForInit SEMI ForCondMark ForCondition SEMI ForStepMark ForStep RPAREN ForBodyMark Statement
					|
					(SingleStatement_findAny) Designator Assignop Designator DOT FINDANY LPAREN Expr RPAREN SEMI
					|
					(SingleStatement_map) Designator Assignop Designator DOT MAP LPAREN IDENT ARROW MapMark Expr RPAREN SEMI
			  		;

ForInit ::= (ForInit_ds) DesignatorStatement
			|
			(ForInit_e) /* epsilon */
			;

ForStep ::= (ForStep_ds) DesignatorStatement
			|
			(ForStep_e) /* epsilon */
			;

ForCondition ::= (ForCondition_c) Condition
				|
				(ForCondition_e) /* epsilon */
				;

ElseStmt ::= 	(ElseStmt_yes) ELSE ElseMark Statement
				|
				(ElseStmt_no) /* epsilon */
				;

Statements ::= (Statements) LBRACE StatementList RBRACE;

IfCondition ::= (IfCondition_c) Condition
				|
				(IfCondition_error) error:e
				{: parser.report_error("oporavak od greske u uslovu if naredbe. Linija: " + eleft, null); :}
				;

Condition ::= (Condition) CondTermList;

CondTermList ::= 	(CondTermList_or) CondTermList OR CondTerm
				 	|
					(CondTermList_ct) CondTerm
					;

CondTerm ::= (CondTerm) CondFactList;

CondFactList ::= 	(CondFactList_and) CondFactList AND CondFact 
				 	|
					(CondFactList_cf) CondFact
					;
				
CondFact ::= 	(CondFact_one) AddopTermList
				| 
				(CondFact_relop) AddopTermList Relop AddopTermList
				;	
			     		
DesignatorStatement ::= (DesignatorStatement_assign) Designator Assignop Expr
						|
						(DesignatorStatement_error) error:e
						{: parser.report_error("oporavak od greske u iskazu dodele. Linija: " + eleft, null); :}
						|
						(DesignatorStatement_meth) Designator LPAREN ActPars RPAREN 
						|
						(DesignatorStatement_inc) Designator INC
						|
						(DesignatorStatement_dec) Designator DEC
						;
						
ActPars ::= (ActPars_rec) ActParsOne ActParsMore
			|
			(ActPars_e)
			;

ActParsMore ::= (ActParsMore_comma) COMMA ActParsOne ActParsMore
				|
				(ActParsMore_e) /* epsilon */
				;
				
ActParsOne ::= 	(ActParsOne) Expr;
						
Expr ::= 	(Expr_term) AddopTermList
			|
			(Expr_ternary) Condition QUESTION Expr TernaryMark COLON Expr
			;
		 
AddopTermList ::= 	(AddopTermList_add) AddopTermList Addop Term
					|
					(AddopTermList_term) Term
					;
   

Term ::= (Term) MulopFactorList
		 ;

MulopFactorList ::= (MulopFactorList_mul) MulopFactorList Mulop Factor
					|
					(MulopFactorList_factor) Factor
					;
			
Factor ::=	(Factor_one) FactorSub
			|
			(Factor_unary) MINUS FactorSub
			;

FactorSub ::= 	(FactorSub_var) Designator
				|
				(FactorSub_meth) Designator LPAREN ActPars RPAREN
		   		|
		   		(FactorSub_n) NUMBER
		   		|
		   		(FactorSub_c) CHARACTER
		   		|
		   		(FactorSub_b) BOOL
		   		|		   
		   		(FactorSub_new_array) NEW Type LBRACKET Expr RBRACKET
		   		|		   
		   		(FactorSub_new_record) NEW Type
		   		|
		   		(FactorSub_expr) LPAREN Expr RPAREN
		   		;
		   		
Designator ::= 	(Designator_var) IDENT
				|
				(Designator_len) Designator DOT LEN
				|
				(Designator_arr) DesignatorArr LBRACKET Expr RBRACKET
				;

DesignatorArr ::= (DesignatorArr) Designator;

Assignop ::= (Assignop) ASSIGN;

Addop ::= (Addop_plus) PLUS
		  |
		  (Addop_minus) MINUS
		  ;

Mulop ::= (Mulop_mul) MULT
		  |		  
		  (Mulop_div) DIV
		  |
		  (Mulop_mod) MOD
		  ;
		  	  
Relop::=    (Relop_eq) EQ
            |
			(Relop_neq) NEQ
			|
			(Relop_gt) GT
			|
			(Relop_gte) GTE
			|
			(Relop_lt) LT
			|
			(Relop_lte) LTE
			;

